version: '2.1'

services:
  backend:
    build: ./backend
    entrypoint: node src/index.js
    ports:
      - "3000:3000"
    env_file: ./backend/.env
    volumes:
      - ./backend:/backend
      - /backend/node_modules
