version: '2.3'

services:
  web-socket-server-test:
    env_file: ./backend/.env.example
    entrypoint: npm test
    build:
      context: ./backend
      target: web-socket-server
    volumes:
      - ./backend/web-socket-server:/web-socket-server
      - /web-socket-server/node_modules

  http-server-test:
    env_file: ./backend/.env.example
    entrypoint: npm test
    build:
      context: ./backend
      target: http-server
    volumes:
      - ./backend/http-server:/http-server
      - /http-server/node_modules

  common-test:
    env_file: ./backend/.env.example
    entrypoint: npm test
    build:
      context: ./backend
      target: common
    volumes:
      - ./backend/common:/common
      - /common/node_modules

  http-server:
    build:
      context: ./backend
      target: http-server
    env_file: ./backend/.env
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:4000/health_check"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./backend/http-server:/http-server
      - /http-server/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
      - rabbitmq

  web-socket-server:
    build:
      context: ./backend
      target: web-socket-server
    env_file: ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend/web-socket-server:/web-socket-server
      - /web-socket-server/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
      - rabbitmq

  command-bot:
    build:
      context: ./backend
      target: command-bot
    env_file: ./backend/.env
    volumes:
      - ./backend/command-bot:/command-bot
      - /command-bot/node_modules
    links:
      - rabbitmq

  postgres:
    image: postgres:9.6-alpine
    ports:
      - 5432
    env_file: ./backend/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "8080:15672"
      - "5672:5672"
      - "25675:25676"

  common-base:
    build:
      context: ./backend
      target: common
    env_file: ./backend/.env
    volumes:
      - ./backend/common:/common
      - /common/node_modules

  migrate-up:
    extends: common-base
    entrypoint: node_modules/.bin/sequelize db:migrate --config src/config/sequelize.js --migrations-path src/ports/sequelize/migrations/
    depends_on:
      postgres:
        condition: service_healthy

  migrate-down:
    extends: common-base
    entrypoint: node_modules/.bin/sequelize db:migrate:undo --config src/config/sequelize.js --migrations-path src/ports/sequelize/migrations/
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    depends_on:
      http-server:
        condition: service_healthy
    links:
      - http-server
      - web-socket-server
