version: '2.1'

services:
  backend:
    build: ./backend
    entrypoint: node src/bin/server.js
    ports:
      - "4000:4000"
    env_file: ./backend/.env
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:4000/health_check"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./backend:/backend
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
      - rabbitmq

  command-bot:
    build: ./backend
    entrypoint: node src/bin/command-bot.js
    env_file: ./backend/.env
    volumes:
      - ./backend:/backend
    links:
      - rabbitmq

  postgres:
    image: postgres:9.6-alpine
    ports:
      - 5432
    env_file: ./backend/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "8080:15672"
      - "5672:5672"
      - "25675:25676"

  migration-base:
    build: ./backend
    env_file: ./backend/.env
    volumes:
      - ./backend:/backend

  migrate-up:
    extends: migration-base
    entrypoint: node_modules/.bin/sequelize db:migrate --config src/config/sequelize.js --migrations-path src/ports/sequelize/migrations/
    depends_on:
      postgres:
        condition: service_healthy

  migrate-down:
    extends: migration-base
    entrypoint: node_modules/.bin/sequelize db:migrate:undo --config src/config/sequelize.js --migrations-path src/ports/sequelize/migrations/
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    depends_on:
      backend:
        condition: service_healthy
    links:
      - backend
