version: '2.1'

services:
  backend:
    build: ./backend
    entrypoint: node src/index.js
    ports:
      - "3000:3000"
    env_file: ./backend/.env
    volumes:
      - ./backend:/backend
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres

  postgres:
    image: postgres:9.6-alpine
    ports:
      - 5432
    env_file: ./backend/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  migration-base:
    build: ./backend
    env_file: ./backend/.env
    volumes:
      - ./backend:/backend

  migrate-up:
    extends: migration-base
    entrypoint: node_modules/.bin/sequelize db:migrate --config src/config/database.js --migrations-path src/database/migrations/
    depends_on:
      postgres:
        condition: service_healthy

  migrate-down:
    extends: migration-base
    entrypoint: node_modules/.bin/sequelize db:migrate:undo --config src/config/database.js --migrations-path src/database/migrations/
    depends_on:
      postgres:
        condition: service_healthy
